### ISSUE TITLE
reboot -f in installer.sh

### ISSUE THREAD

**Issue by glueckself** [Psychokiller1888/ProjectAliceInstaller#5]
Hi!

I'm trying to install Project Alice and I've noticed a "reboot -f" at the end of the installer.sh-script.
Forcing the reboot might cause issues with file systems or databases because of the unclean shutdown. Even a simple reboot might cause problems because it aborts everything else that might be going on in other sessions.

Is there reason for doing a (forced) reboot right after?
If not, I would propose to replace it with a message ("Please reboot at your convenience"/...).

**Comment by Psychokiller1888** [comment]
It does a reboot to actually reload everything and start Alice. Sure I like the "Reboot at your convenience" but it is a part that can be automated. Now why I force the reboot, mmmmh, I think because I had issues with a standard reboot. I guess we could try with a "shutdown -r"?

**Comment by glueckself** [comment]
As the script requires manual inputs, it cannot be used to "fully" automatically install Alice, and I think reboot is a simple enough step that doesn't need automating (unlike installing the dependencies and configuring everything).
Maybe a "Do you want to reboot now?" prompt and if answer negatively, the "Reboot at your convenience"?

The reason I'm bringing this up is because I'm running the main Alice unit on a x86-64 VM on my Server (I added architecture-dependent snips repository). I'm probably going to install it a few Times while tinkering around and I'd prefer to keep the VM running as I'm sure that I'll be doing stuff in another session. If you say that you don't want to support this use case, then it's probably enough to change to "shutdown -r".

On a side note, do you prefer a single pull request that includes multiple unrelated fixes or can I make a single pull request ("fixes running for the first time")?

Oh, and thanks to all of you for the great work! :) I hated that the snips console is a unmaintainable mess with a broken forking and sharing system. Alice does it right.

**Comment by Psychokiller1888** [comment]
I'm open to any suggestions, don't worry. You have a point saying that the installer is anyway not completly automated as requiring manual inputs where the image is completly automated. We can change it to a "Please reboot now (or suffer the consequences of a non working Alice)" for me, it's not a problem.

Re fixes, as long as the changelog is not 100+ files to review, I'm ok with pull requests broken down with multiple commits that fix clear parts.

We made the whole module, console stuff exactly for what you describe, but mostly the inability to cooperate on skill development without sharing a same account. Happy you like it already in alpha, because believe it or not, there's much more coming to this for the v1.0 but there's still a long road to bring something that was perfectly fitting at home for years to something that is universal and works for everybody :)

**Comment by glueckself** [comment]
> I'm open to any suggestions, don't worry.

Oh, sorry if I left the impression that I thought otherwise. Really sorry.

Ok, I'll implement that.

I'm looking forward to it :)
My goal is to have Alice switch the ASR to a general one (a full kaldi instance with gigabytes of language models) to dictate. Something like...
> Me: Alice, please send a text to Max via jabber.
> Alice: Ready, whats the message?
> Me: Hey, how are you? Let's meet for a drink.
> Alice: Message sent.

It's OK if it understands "trunk" instead of "drink" in the beginning :D

EDIT: fixed formatting

**Comment by Psychokiller1888** [comment]
This is partly possible through a general words slot that is available and through, otherwise, google asr implementation. What's on the back burner is a partial google query if words aren't recognized to complete and help the local asr. And also adding support for other ASRs

**Comment by glueckself** [comment]
I think we're going off topic here, I'll join the discord later to continue brainstorming :)
